name: auto-check-changed-files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  auto-check-changed-files:
    runs-on: ubuntu-latest
  
    steps:
  
    # checkout repo
    - uses: actions/checkout@v2

    # setup python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    # install requirements.txt if it exists
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # setup node
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
    
    # install dependencies if package.json exists
    - name: Install js dependencies
      run: if [ -f package.json ]; then npm install; fi

    # use action to get files that changed
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
       token: ${{ secrets.GITHUB_TOKEN }}

    # bash script to get list of changed files and check each file
    # set permission of script and execute
    - name: Checking files
      run: |
        echo "job: running script to check changed files:"
        chmod +x ./.github/workflows/auto-check-changed-files.sh
        ./.github/workflows/auto-check-changed-files.sh
        echo "job: Done"